name: Machine Learning OPs CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  retrain-and-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mlflow pandas scikit-learn

    - name: Run MLflow Project (Re-training Model)
      run: |
        mlflow run MLProject --env-manager local

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker Image using MLflow
      run: |
        - name: Build Docker Image using MLflow
      run: |
        # 1. Cari file meta.yaml yang berada di dalam folder artifacts/model secara global
        META_FILE=$(find . -path "*/artifacts/model/../../meta.yaml" | head -n 1)
        
        # 2. Ambil baris run_id dari file tersebut secara akurat
        export DYNAMIC_RUN_ID=$(grep "run_id:" "$META_FILE" | awk '{print $2}' | tr -d '"' | tr -d "'")
        
        echo "Berhasil mengekstrak Run ID dari meta.yaml: $DYNAMIC_RUN_ID"
        
        # 3. Bangun Docker menggunakan URI runs:/ yang sudah dipetakan secara dinamis
        mlflow models build-docker -m "runs:/$DYNAMIC_RUN_ID/model" -n "${{ secrets.DOCKERHUB_USERNAME }}/mlflow-model:latest" --env-manager local

    - name: Push Docker Image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/mlops-dropout-model:latest